/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: ผมเรียนกราฟิก (https://sketchfab.com/ramakienx)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/luffy-hat-3af7f978b35b49d1a51bf1f3aba90923
Title: Luffy Hat
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

const Hat = (props) => {
  const { nodes, materials } = useGLTF("/luffy_hat (1).glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_5.geometry}
        material={materials.line}
      />
    </group>
  );
};

useGLTF.preload("/luffy_hat (1).glb");
export default Hat;
